# Generated by Django 4.0.3 on 2022-04-13 11:27

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Course')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Course Description')),
                ('image', models.ImageField(upload_to='courses/', verbose_name='Course Image')),
                ('date_of_creating', models.DateField(default=django.utils.timezone.now, verbose_name='Date of creating')),
                ('creator', models.ForeignKey(on_delete=models.SET('Unknown'), related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='Creator')),
                ('students', models.ManyToManyField(blank=True, related_name='current_courses', to=settings.AUTH_USER_MODEL, verbose_name='Students')),
            ],
        ),
    ]
