# Generated by Django 4.0.3 on 2022-04-13 11:54

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('study_courses_app', '0002_course_course_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Lesson')),
                ('order', models.PositiveIntegerField(verbose_name='Lesson Order')),
                ('description', models.TextField(blank=True, verbose_name='Lesson Description')),
                ('image', models.ImageField(upload_to='courses/modules/lessons/<django.db.models.fields.CharField>/', verbose_name='Module Image')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Theme')),
                ('order', models.PositiveIntegerField(verbose_name='Theme Order')),
                ('description', models.TextField(blank=True, verbose_name='Theme Description')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Theme Content')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='study_courses_app.lesson', verbose_name='Lesson')),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Module')),
                ('order', models.PositiveIntegerField(verbose_name='Module Order')),
                ('description', models.TextField(verbose_name='Module Description')),
                ('image', models.ImageField(upload_to='courses/modules/<django.db.models.fields.CharField>/', verbose_name='Module Image')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='study_courses_app.course', verbose_name='Course')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='study_courses_app.module', verbose_name='Module'),
        ),
    ]
