# Generated by Django 4.0.3 on 2022-04-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_courses_app', '0003_lesson_theme_module_lesson_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='image',
            field=models.ImageField(upload_to='courses/modules/lessons/', verbose_name='Module Image'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, verbose_name='Module Description'),
        ),
        migrations.AlterField(
            model_name='module',
            name='image',
            field=models.ImageField(upload_to='courses/modules/', verbose_name='Module Image'),
        ),
    ]
