# Generated by Django 4.0.3 on 2022-04-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_courses_app', '0005_alter_lesson_image_alter_module_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='order',
            field=models.PositiveIntegerField(blank=True, verbose_name='Module Order'),
        ),
    ]
