# Generated by Django 4.0.3 on 2022-04-21 18:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('study_courses_app', '0008_alter_course_course_status_alter_theme_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='old_students',
            field=models.ManyToManyField(blank=True, related_name='old_courses', to=settings.AUTH_USER_MODEL, verbose_name='Old Students'),
        ),
    ]
