# Generated by Django 4.0.3 on 2022-04-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study_courses_app', '0009_course_old_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='sound',
            field=models.FileField(blank=True, upload_to='courses/modules/lessons/themes/sounds/', verbose_name='Theme Sound'),
        ),
    ]
