# Generated by Django 4.0.3 on 2022-04-09 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_commentanswer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentanswer',
            options={'ordering': ['date_of_creating']},
        ),
    ]
