# Generated by Django 4.0.3 on 2022-04-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_alter_post_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Deleted', 'Deleted')], default='Published', max_length=10, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='commentanswer',
            name='status',
            field=models.CharField(choices=[('Published', 'Published'), ('Deleted', 'Deleted')], default='Published', max_length=10, verbose_name='Status'),
        ),
    ]
