# Generated by Django 4.0.3 on 2022-04-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_comment_status_commentanswer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(upload_to='news/', verbose_name='Image'),
        ),
    ]
