# Generated by Django 4.0.3 on 2022-04-07 18:46

import ckeditor_uploader.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last Name')),
                ('photo', models.ImageField(height_field=250, upload_to='', verbose_name='Photo', width_field=250)),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description')),
                ('detail_info', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Detail Info')),
            ],
        ),
        migrations.CreateModel(
            name='TeacherContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator], verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone')),
                ('telegram', models.CharField(blank=True, max_length=50, verbose_name='Telegram')),
                ('vk', models.CharField(blank=True, max_length=50, verbose_name='VK')),
                ('instagram', models.CharField(blank=True, max_length=50, verbose_name='Instagram')),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contact_info', to='teachers_app.teacher')),
            ],
        ),
    ]
