# Generated by Django 4.0.3 on 2022-04-07 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0002_remove_teacher_detail_info_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='photo',
        ),
    ]
