# Generated by Django 4.0.3 on 2022-04-07 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0003_remove_teacher_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Photo'),
        ),
    ]
