# Generated by Django 4.0.3 on 2022-04-07 19:04

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0005_teacher_detail_info_teacher_short_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='detail_info',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Detail Info'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Description'),
        ),
    ]
