# Generated by Django 4.0.3 on 2022-04-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0008_teacher_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
