# Generated by Django 4.0.3 on 2022-04-22 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers_app', '0011_alter_teacher_slogan'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualLessonApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Person')),
                ('phone', models.CharField(max_length=100, verbose_name='Person Phone')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('status', models.CharField(choices=[('OPENED', 'Opened'), ('IN_WORK', 'In Work'), ('CLOSED', 'Closed')], default='OPENED', max_length=10, verbose_name='Status')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_lessons_applications', to='teachers_app.teacher')),
            ],
        ),
    ]
