# Generated by Django 4.0.3 on 2022-04-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_profile_instagram_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=100, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='telegram_link',
            field=models.CharField(blank=True, max_length=100, verbose_name='Telegram'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='vk_link',
            field=models.CharField(blank=True, max_length=100, verbose_name='VK'),
        ),
    ]
