# Generated by Django 4.0.3 on 2022-04-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0003_alter_profile_instagram_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, upload_to='users/', verbose_name='Photo'),
        ),
    ]
