# Generated by Django 4.0.3 on 2022-04-10 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Course',
            new_name='SchoolCourse',
        ),
        migrations.RenameModel(
            old_name='CourseDescriptionField',
            new_name='SchoolCourseDescriptionField',
        ),
    ]
