# Generated by Django 4.0.3 on 2022-04-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0003_schoolcourse_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcourse',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
