# Generated by Django 4.0.3 on 2022-04-19 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0004_alter_schoolcourse_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='Person')),
                ('phone', models.CharField(max_length=100, verbose_name='Person Phone')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_applications', to='courses_app.schoolcourse')),
            ],
        ),
    ]
