# Generated by Django 4.0.3 on 2022-04-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses_app', '0006_alter_schoolcourseapplication_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcourseapplication',
            name='phone',
            field=models.CharField(max_length=100, verbose_name='Person Phone'),
        ),
    ]
